version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017

  spring-mongodb:
    image: spring-mongodb
    container_name: spring-mongodb
    ports:
      - 8081:8081

  spring-mongodb-1:
    image: spring-mongodb
    container_name: spring-mongodb-1
    ports:
      - 8082:8081